"""
Remove duplicate occurrences by ID. Used after the C3 batch where my newer,
richer entries duplicated older sparser ones — we keep the newer entries.

Also bumps the master priority of the kept entries to the higher of the two,
since the older entries had higher master priorities (they were ranked when
the Roman timeline didn't exist).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MASTER_PY = ROOT / "v2" / "data" / "master.py"
sys.path.insert(0, str(ROOT))

# (id_to_delete, id_to_promote, new_master_priority_for_promoted_entry)
PURGE_PLAN = [
    # First pass (already applied; harmless re-run if entry no longer exists).
    (1_000_105, 1_005_708, 958_935),   # Plague of Justinian
    (1_001_576, 1_005_701, 880_000),
    (1_001_735, 1_005_707, 985_560),
    (1_004_982, 1_005_663, 945_000),
    (1_004_984, 1_005_672, 948_000),
    (1_004_985, 1_005_680, 920_000),
    (1_004_989, 1_005_692, 920_000),
    (1_004_995, 1_005_704, 948_000),
    # Second pass: my person entry for Marcus Aurelius (1_005_671) duplicates
    # the existing one (1_000_096). Delete mine; bump existing master priority.
    (1_005_671, 1_000_096, 920_000),
    # Third pass (Phase C4 dupes).
    (1_000_119, 1_005_758, 840_000),   # Battle of Stamford Bridge — my entry is richer
    (1_000_632, 1_005_745, 953_610),   # Sutton Hoo — bump mine to preserve old master priority
    (1_000_636, 1_005_746, 929_152),   # Lindisfarne Gospels — bump mine
    (1_000_639, 1_005_754, 816_426),   # Battle of Maldon — bump mine
    (1_005_011, 1_005_750, 920_000),   # Battle of Edington
    # Fourth pass (Phase C5 dupes).
    (1_000_664, 1_005_798, 929_061),
    (1_000_665, 1_005_799, 858_394),
    (1_000_676, 1_005_813, 857_671),
    (1_000_678, 1_005_817, 816_155),
    (1_000_679, 1_005_818, 857_581),
    (1_000_680, 1_005_820, 905_776),
    (1_000_681, 1_005_821, 967_870),
    (1_000_687, 1_005_833, 905_596),
    (1_000_688, 1_005_834, 857_310),
    (1_003_619, 1_005_795, 817_780),
    (1_000_176, 1_005_824, 970_487),   # Restoration of Charles II
    (1_000_181, 1_005_832, 995_126),   # Glorious Revolution
    (1_000_660, 1_005_790, 858_755),   # Battle of Towton
    (1_000_138, 1_005_772, 870_397),   # Battle of Bannockburn
    (1_000_141, 1_005_774, 911_372),   # Battle of Crécy
    (1_000_143, 1_005_780, 990_433),   # Canterbury Tales
    (1_000_127, 1_005_762, 911_552),   # Murder of Thomas Becket
    (1_003_718, 1_005_783, 850_000),   # Owain Glyndŵr's revolt
    (1_003_719, 1_005_814, 850_000),   # Personal Rule of Charles I
    (1_004_056, 1_005_800, 857_623),   # Execution of Anne Boleyn
    (1_004_269, 1_005_776, 920_000),   # Battle of Poitiers (1356)
    # Fifth pass (Phase C6 dupes — auto-generated by purge_c6_dupes.py).
    (1_000_197, 1_005_840, 990162),
    (1_000_220, 1_005_849, 993051),
    (1_000_222, 1_005_850, 880000),
    (1_000_229, 1_005_853, 870000),
    (1_000_245, 1_005_854, 830000),
    (1_000_248, 1_005_855, 868412),
    (1_000_252, 1_005_859, 957130),
    (1_000_260, 1_005_863, 957040),
    (1_000_261, 1_005_864, 969856),
    (1_000_286, 1_005_876, 956679),
    (1_000_287, 1_005_877, 909838),
    (1_000_299, 1_005_881, 980144),
    (1_000_305, 1_005_882, 956408),
    (1_000_320, 1_005_886, 969404),
    (1_000_342, 1_005_892, 996209),
    (1_000_344, 1_005_893, 979603),
    (1_000_350, 1_005_895, 955957),
    (1_000_400, 1_005_917, 968412),
    (1_000_470, 1_005_841, 954332),
    (1_000_693, 1_005_838, 905505),
    (1_000_694, 1_005_839, 928700),
    (1_000_707, 1_005_860, 905235),
    (1_000_713, 1_005_866, 905054),
    (1_000_715, 1_005_873, 815794),
    (1_000_716, 1_005_869, 860000),
    (1_000_725, 1_005_884, 855415),
    (1_000_727, 1_005_885, 904964),
    (1_000_729, 1_005_889, 904874),
    (1_000_730, 1_005_891, 928520),
    (1_000_734, 1_005_897, 815343),
    (1_000_738, 1_005_900, 904783),
    (1_000_739, 1_005_901, 815162),
    (1_000_740, 1_005_902, 854964),
    (1_000_744, 1_005_905, 820000),
    (1_000_745, 1_005_906, 854693),
    (1_000_759, 1_005_915, 904603),
    (1_000_779, 1_005_894, 904422),
    # Sixth pass (Phase D Ancient Greece dupes).
    (1_000_062, 1_005_926, 912274),
    (1_000_065, 1_005_935, 872473),
    (1_000_068, 1_005_940, 900000),
    (1_000_069, 1_005_943, 983123),
    (1_000_070, 1_005_944, 971300),
    (1_000_071, 1_005_945, 959386),
    (1_000_072, 1_005_952, 920000),
    (1_000_079, 1_005_990, 959206),
    (1_000_875, 1_005_957, 880000),
    (1_000_876, 1_005_958, 890000),
    (1_000_877, 1_005_959, 880000),
    (1_000_878, 1_005_960, 850000),
    (1_003_034, 1_005_965, 961372),
    (1_003_637, 1_005_920, 910000),
    (1_003_639, 1_005_924, 917329),
    (1_003_641, 1_005_962, 961462),
    (1_004_939, 1_005_946, 920000),
    (1_004_942, 1_005_963, 895000),
    (1_004_943, 1_005_966, 890000),
    (1_004_944, 1_005_984, 948000),
    (1_004_950, 1_005_997, 895000),
    (1_004_951, 1_005_996, 895000),
    # Seventh pass (Phase D Germany dupes).
    (1_000_030, 1_006_021, 997653),
    (1_000_110, 1_006_006, 970848),
    (1_000_114, 1_006_008, 911733),
    (1_000_173, 1_006_034, 982040),
    (1_000_190, 1_006_043, 970397),
    (1_000_238, 1_006_042, 957491),
    (1_000_258, 1_006_068, 969946),
    (1_000_267, 1_006_060, 956949),
    (1_000_269, 1_006_055, 950000),
    (1_000_283, 1_006_069, 930000),
    (1_001_970, 1_006_091, 937184),
    (1_001_981, 1_006_092, 961643),
    (1_003_078, 1_006_031, 983935),
    (1_003_508, 1_006_094, 959928),
    (1_003_509, 1_006_095, 960000),
    (1_003_517, 1_006_081, 880000),
    (1_003_518, 1_006_085, 890000),
    (1_003_519, 1_006_087, 876715),
    (1_003_542, 1_006_047, 913538),
    (1_003_608, 1_006_022, 920000),
    (1_003_611, 1_006_026, 900000),
    (1_003_655, 1_006_028, 984025),
    (1_004_215, 1_006_061, 900000),
    (1_004_601, 1_006_075, 945000),
    (1_004_624, 1_006_082, 890000),
    (1_004_653, 1_006_073, 940000),
]


def main() -> int:
    text = MASTER_PY.read_text(encoding="utf-8")
    deleted = bumped = 0

    for del_id, prom_id, new_master in PURGE_PLAN:
        # Delete block for del_id.
        # Block runs from `    {"id": <del_id>,` to the matching `}},\n`.
        del_str = f"{del_id:_}"
        pat = re.compile(
            rf'    \{{"id": {del_str},.*?\}}\}},\n',
            re.DOTALL,
        )
        new_text, n = pat.subn("", text, count=1)
        if n == 0:
            print(f"  WARN: could not delete id {del_id}")
        else:
            text = new_text
            deleted += 1

        # Bump master priority on prom_id by rewriting its priorities line.
        prom_str = f"{prom_id:_}"
        # Locate the priorities line within the promoted entry's block.
        # The block format has the priorities line as: `     "priorities": {"master": NNN, ...}`
        # We rewrite only the `"master": <num>` value.
        block_pat = re.compile(
            rf'(\{{"id": {prom_str},.*?"priorities":\s*\{{"master": )(\d+)(.*?\}}\}},)',
            re.DOTALL,
        )
        def repl(m: re.Match) -> str:
            current = int(m.group(2))
            if current >= new_master:
                return m.group(0)  # no change
            return f"{m.group(1)}{new_master}{m.group(3)}"
        text, n2 = block_pat.subn(repl, text, count=1)
        if n2 == 0:
            print(f"  WARN: could not bump priority on id {prom_id}")
        else:
            bumped += 1

    MASTER_PY.write_text(text, encoding="utf-8")
    print(f"Deleted {deleted} duplicate blocks; bumped master priority on {bumped} promoted entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
